### ISSUE TITLE
Fix conftest.py

### ISSUE THREAD

**Issue by mohanqxf2** [qxf2/qxf2-page-object-model#107]
I am getting a warning message from conftest.py file
 
'PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.
    if pytest.config.getoption("-I").lower() == 'y':`

**Comment by qxf2** [comment]
@mohanqxf2 - can you please check if this ticket has been fixed and merged?

**Comment by mohanqxf2** [comment]
sure. i can check it
