### ISSUE TITLE
Change the way we figure out the name of the calling module.

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#117]
Change the way we figure out the name of the calling module. We seem to be using non-relative array indexes (e.g.: [4]) and that won't work as we keep adding pytest plugins. We should try to do something more intelligent. E.g.: Check for the string 'test_'?

**Comment by qxf2** [comment]
@rohinigopalqxf2 - afaik, this has been fixed, right? If so, can you please close this issue. If not, just comment here and we will give it the next new contributor.

**Comment by rohinigopalqxf2** [comment]
This is fixed. I do not have rights to close the ticket, kindly close the ticket.
