### ISSUE TITLE
Add visual highlighting to elements being operated upon

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#121]
I used a tool called PAMIE a long while ago. One of its nice features was that it gave a thick yellow highlight around the element being operated upon. 

Can we develop a feature like that? The user should be able to turn on the feature when they are developing and then turn it off during actual test runs.

**Comment by qxf2** [comment]
@PreedhiVivek - please reference your PR here and close this issue once your PR is merged.

**Comment by PreedhiVivek** [comment]
PR : https://github.com/qxf2/qxf2-page-object-model/pull/180
PR merged and hence closing this issue.
