### ISSUE TITLE
Add a new file with test boilerplate

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#129]
We don't have an easy and intuitive way to write a test from scratch. Can we add a simple test_boilerplate.py file to the tests folder? Make sure to add it to the pytest ignore options. 

Btw, let us not add any testrail or tesults boiler plate code. Just imports, method signature, expected/actual pass logic, creating the first page object, registering the driver, creating the test summary, assert and main should do.

**Comment by akkuldn** [comment]
Added the test boilerplate file and code has been merged to master. 
Hereby closing this issue
