### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by yangquan1982** [qxf2/qxf2-page-object-model#134]
MacOS v10.14.5
Try to install dependencies but failed:
`pip3 install -r requirements.txt to install dependencies`
`Collecting to
  Using cached https://files.pythonhosted.org/packages/05/8b/949ffc9ca52aca12b21985f6d97e7946c8c284a638ee15d8851592014fbe/to-0.3.tar.gz
Collecting install
  ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install`

**Comment by nilaya123** [comment]
> MacOS v10.14.5
> Try to install dependencies but failed:
> `pip3 install -r requirements.txt to install dependencies`
> `Collecting to Using cached https://files.pythonhosted.org/packages/05/8b/949ffc9ca52aca12b21985f6d97e7946c8c284a638ee15d8851592014fbe/to-0.3.tar.gz Collecting install ERROR: Could not find a version that satisfies the requirement install (from versions: none) ERROR: No matching distribution found for install`



> MacOS v10.14.5
> Try to install dependencies but failed:
> `pip3 install -r requirements.txt to install dependencies`
> `Collecting to Using cached https://files.pythonhosted.org/packages/05/8b/949ffc9ca52aca12b21985f6d97e7946c8c284a638ee15d8851592014fbe/to-0.3.tar.gz Collecting install ERROR: Could not find a version that satisfies the requirement install (from versions: none) ERROR: No matching distribution found for install`

Hi Edward,

I tried to reproduce the issue on same MAC version, MacOS v10.14.5 but was not able to reproduce.
Which Python Version you tried?  I have tried 3.7.4. Also can you please try the same on virtual enviornment? 

Thanks,

**Comment by yangquan1982** [comment]
I'm using Python 3.7.4 and added it to PATH environment variable, still got the same issue:
`Edwards-MBP:qxf2-page-object-model quan.yang$ Python3 --version
Python 3.7.4`
`Edwards-MBP:qxf2-page-object-model quan.yang$ echo $PATH`
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/chromedriver:/usr/local/opt/python/bin/python3.7:/usr/local/go/bin`
`Edwards-MBP:qxf2-page-object-model quan.yang$ pip3 install -r requirements.txt to install dependencies`
`Collecting to`
 ` Using cached https://files.pythonhosted.org/packages/05/8b/949ffc9ca52aca12b21985f6d97e7946c8c284a638ee15d8851592014fbe/to-0.3.tar.gz`
`Collecting install`
`  ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install`

**Comment by yangquan1982** [comment]
I tried to run `pip3 install -r requirements.txt to install dependencies` inside of `virtualenv` but still failed:
`Edwards-MBP:qxf2-page-object-model quan.yang$ pipenv shell`
`Launching subshell in virtual environment…`
`bash-3.2$  . /Users/quan.yang/.local/share/virtualenvs/quan.yang-gm9jLPbL/bin/activate`
`(quan.yang) bash-3.2$`
`(quan.yang) bash-3.2$ pip3 install -r requirements.txt to install dependencies`
`Collecting to`
`  Using cached` `https://files.pythonhosted.org/packages/05/8b/949ffc9ca52aca12b21985f6d97e7946c8c284a638ee15d8851592014fbe/to-0.3.tar.gz`
`Collecting install`
`  ERROR: Could not find a version that satisfies the requirement install (from versions: none)`
`ERROR: No matching distribution found for install`

**Comment by nilaya123** [comment]
Can you please try below command on your setup,
python3 -m install pip install -r requirements.txt

Please check this link : https://stackoverflow.com/questions/38159462/no-matching-distribution-found-for-install

**Comment by yangquan1982** [comment]
Yes, that works,
I typed `sudo python3 -m pip install -r requirements.txt` with `sudo` permission
still having two warnings:
`WARNING: The directory '/Users/quan.yang/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`
`WARNING: The directory '/Users/quan.yang/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`
but it doesn't matter, thanks.
