### ISSUE TITLE
Log messages must have the right module listed

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#135]
I only see Base_Page.write() as the calling modulein the log messages. That makes debugging really hard. I think this broke with the introduction of loguru but I could be wrong.

Example of a bad log message:
2019-07-11 16:57:08.656 | INFO     | utils.Base_Logging:write:60 - conditional_write | Found the expected item 'Gary Bio Sandalwood SPF-50' in the cart

^Notice that `utils.Base_Logging:write:60 - conditional_write` is completely useless. I want to know  something more about who called that message.

**Comment by qxf2** [comment]
@rohinigopalqxf2 - can this be closed? I believe https://github.com/qxf2/qxf2-page-object-model/pull/174 solved this issue?

**Comment by rohinigopalqxf2** [comment]
Yes. We can close this.
