### ISSUE TITLE
Add a utility to convert all screenshots into one gif

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#139]
We end up producing many screenshots per test as part of test execution. It would be nice if we added a utility function to produce a gif based on all the different screenshots. The test can call the utility function separately if needed. 

This is also really useful when we want to share demos of the test.

**Comment by rohanj-qxf2** [comment]
A new utility Gif_Maker is added to convert all screenshots into a single GIF file
