### ISSUE TITLE
Add pytest markers support

### ISSUE THREAD

**Issue by rohanj-qxf2** [qxf2/qxf2-page-object-model#154]
Group the web related tests with 'GUI' marker ,mobile tests with 'Mobile' and so on . This would be helpful to demonstrate the use pf pytest markers

**Comment by rahul-qxf2** [comment]
Raised following PR:
https://github.com/qxf2/qxf2-page-object-model/pull/163/commits

**Comment by rahul-qxf2** [comment]
closing issue as changes are already there through another merge request(#reuest170)
