### ISSUE TITLE
Use better variable names for the conf files imported in page_objects/Base_Page.py

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#162]
I noticed that we are importing modules using lazy names. These two lines in particular are bad:

```
from conf import remote_credentials as Conf
from .conf import base_url_conf as conf

```

Notice both are using a generic 'conf' name and to make matters worse, one uses a uppercase C and the other uses lower case c and we have a directory/package names conf as well. 

Use better variable names for the conf files imported in page_objects/Base_Page.py . Try using remote_credentials_conf and base_url_conf or just use the `import conf.remote_credentials` and then reference the variable correctly where it is called.

This also affect PageFactory ... we should really stop using the word 'conf' after an 'import as'

**Comment by rahul-qxf2** [comment]
@arunkumarmuralidharan ,

Below is my progress:
1. Made the import statements generic as below- in the Base Page.
import conf.remote_credentials
import conf.base_url_conf 
Also made the import statement generic in the PageFactory.py as we are importing the same in the Base Page:
import conf.base_url_conf
Now while testing this change with test_example_form. py - I am getting following exception:
--------------------------------------------------
Exception when trying to run test:c:/Users/Rahul Bhave Qxf2/code/rahul-qxf2/qxf2-page-object-model/tests/test_example_form.py
Python says:name 'Conf' is not defined
Traceback (most recent call last):
  File "c:/Users/Rahul Bhave Qxf2/code/rahul-qxf2/qxf2-page-object-model/tests/test_example_form.py", line 167, in <module>
    remote_build_name=options.remote_build_name)
  File "c:/Users/Rahul Bhave Qxf2/code/rahul-qxf2/qxf2-page-object-model/tests/test_example_form.py", line 145, in test_example_form
    assert expected_pass == actual_pass, "Test failed: %s"%__file__
AssertionError: Test failed: c:/Users/Rahul Bhave Qxf2/code/rahul-qxf2/qxf2-page-object-model/tests/test_example_form.py
------------------------------------------------------------------
if I change the import statement import conf.remote_credentials as Conf in the BasePage the test passes successfully. The error log lead me to the option_parser.py file. I may need some more time to fix this.

**Comment by rahul-qxf2** [comment]
Raised following PR:
https://github.com/qxf2/qxf2-page-object-model/pull/167

**Comment by rahul-qxf2** [comment]
One follow-up PR 167 raised. Since follow up PR 167 is closed now. This issue can be closed now.
