### ISSUE TITLE
Try to get rid of trailing_slash as an argument to Base_Page

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#165]
This was introduced to avoid the '//' and no slash in URLs. I think we can be smart here and when we go to a URL, we can simply remove the double slash and also be smart when we add parts of URLs to always have one slash in between. 

The benefit will be readability in Page Factory and in tests.

**Comment by rahul-qxf2** [comment]
Raised PR
https://github.com/qxf2/qxf2-page-object-model/pull/168

**Comment by rahul-qxf2** [comment]
This is merged hence closing the issue
