### ISSUE TITLE
Test putting out a run-time error when no screenshots are captured.

### ISSUE THREAD

**Issue by akkuldn** [qxf2/qxf2-page-object-model#181]
When no screenshots are captured, we are hitting an error "Zero images were written" and the test fails. However, it doesn't raise any error when at least one simple test like clicking of a button is added.
![boilerplate](https://user-images.githubusercontent.com/52410419/72699650-41d35900-3b6f-11ea-9916-46b3d80be2ca.JPG)

**Comment by akkuldn** [comment]
Please test with the test_boilerplate file from the given branch:
https://github.com/qxf2/qxf2-page-object-model/tree/test_boilerplate

**Comment by kirancv4** [comment]
Resolved this issue ...so closing this.
