### ISSUE TITLE
Base_Logging.set_log has no return value

### ISSUE THREAD

**Issue by ikostan** [qxf2/qxf2-page-object-model#209]
Hello there.

I am referring to [Base_Logging](https://github.com/qxf2/qxf2-page-object-model/blob/5f21b04cb50862a577e24eccdbe7d93b507e5ca2/utils/Base_Logging.py) class method, line 20:
`        
self.log = self.set_log(self.log_file_name,self.level,self.format) 
`
Actual result for self.log will be always None since set_log function has no return value. Therefore, there is no need to declare self.log.

This is minor issue. 

Thanks.

**Comment by qxf2** [comment]
Reopening because we haven't yet fixed this issue.
