### ISSUE TITLE
The call to report tesults in pytest_terminal_summary is breaking pattern

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#210]
See: https://github.com/qxf2/qxf2-page-object-model/blob/5f21b04cb50862a577e24eccdbe7d93b507e5ca2/conftest.py#L254

We seem to be doing if, elif and then if again. If we chose the if-elif pattern, then we must stick with it. Alternate is that we can simply do three separate if statements.

**Comment by rahul-qxf2** [comment]
Created following PR for this issue:
https://github.com/qxf2/qxf2-page-object-model/pull/212

Circle CI tests are passing now for this PR as well.

**Comment by rahul-qxf2** [comment]
Code merged into Master, circle ci tests are passing on master as well:
https://app.circleci.com/pipelines/github/qxf2/qxf2-page-object-model/74/workflows/4fd48a43-6550-4169-93de-bbfc56420466/jobs/813

Moving this ticket as Done.
