### ISSUE TITLE
DriverFactory is a mess. Please clean up the code.

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#213]
The code in our DriverFactory is very poor. There are way too many issues to list but here are a few:

a) doc string is not very clear 
b) too many multiline print() 
c) run_local, run_mobile doc strings are not correct 
d) hardcoded ports in run_mobile 
e) missing methods for other browsers 
f) whitespace and new line inconsistency 
g) filename is inconsistent with everything else 
h) no modularization at all - why are there so many nested if-else?, why isn't each browser and each option a separate class/module?
i) methods are too long - how do we have a 100 line method??
j) method signature is bad - look at the run_mobile method
k) method interface is unintuitive

Ideally, the interface would just have:
a) get_driver()
b) get_local() with conditional imports for different browsers ... each browser has its own module
c) get_remote() with conditional imports for different remote options ... each remote option has its own module

**Comment by akkuldn** [comment]
Im working on this, The updates can be found in the following trello card https://trello.com/c/V7XhN5RO/38-refactor-driverfactory
