### ISSUE TITLE
Please fix unused import statements identified by codacy

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#217]
Codacy says we have 21(!) unused import statements. Please fix them up.

https://app.codacy.com/manual/qxf2/qxf2-page-object-model/issues?bid=16560353&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE3MjAiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by rahul-qxf2** [comment]
Closing the issue as following PR got merged.
`https://github.com/qxf2/qxf2-page-object-model/pull/237`
