### ISSUE TITLE
Fix the bare except statement in Base_API

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#220]
In Line 107 of page_objects/Base_API.py, we seem to have a bare except clause. Please fix it.

**Comment by rahul-qxf2** [comment]
@qxf2 , When I checked the `Base_API.py` I see following except clause in Line 108

`except (HTTPError,URLError) as e:`

Are you referring the same statement?

**Comment by rahul-bhave** [comment]
@arunkumarmuralidharan , @qxf2 , would you please comment on below:

> @qxf2 , When I checked the `Base_API.py` I see following except clause in Line 108
> 
> `except (HTTPError,URLError) as e:`
> 
> Are you referring the same statement?

**Comment by qxf2** [comment]
@rahul-bhave - the line seems to have moved to 104 now. 'Bare except' means we are using just the word 'except' in the except statement.

https://github.com/qxf2/qxf2-page-object-model/blob/2fbdcdf3fe1789f75da5ee4a8f19c0a3ea9207ca/endpoints/Base_API.py#L104

**Comment by rahul-bhave** [comment]
> @rahul-bhave - the line seems to have moved to 104 now. 'Bare except' means we are using just the word 'except' in the except statement.
> 
> https://github.com/qxf2/qxf2-page-object-model/blob/2fbdcdf3fe1789f75da5ee4a8f19c0a3ea9207ca/endpoints/Base_API.py#L104

@qxf2 , @arunkumarmuralidharan ,
I am proposing below except block:
```
except requests.exceptions.RequestException:
raise Exception('Failed to connect to %s' % url) from None
```
Let me know in case you have a comment. After your confirmation, I will share the changes for code review. This will be required in the `get`, `post`, and `delete` method as well.
```
References:
https://github.com/psf/requests/issues/5291
https://www.reddit.com/r/learnpython/comments/524ufd/randomly_receiving_jsondecoderjsondecodeerror/
https://www.python.org/dev/peps/pep-0409/
```

**Comment by qxf2** [comment]
@rahul-bhave - can you elaborate why you chose RequestException when the statement being tried is a response.json()?  

I know you have references, but please explain it in your own words so I don't have to go read and solve this issue for myself.

**Comment by rahul-bhave** [comment]
> @rahul-bhave - can you elaborate why you chose RequestException when the statement being tried is a response.json()? I also did not follow why this would be needed in the get, post and delete methods. We are talking about the bare except and that one's try block is just accessing response.json().
> 
> I know you have references, but please explain it in your own words so I don't have to go read and solve this issue for myself.

@qxf2 , 

Initially, I have given a thought of implementing as below:

```
except (HTTPError,URLError) as e:
            error = e
```

However, response.json() may not always give response code as `200', there may be response code as '500' or '404', in that case, we may have to find the exception in the requests. So I searched for any code snippet with which we will able to capture the exception in the request, I found the following code snippet which can help us:

```
except requests.exceptions.RequestException:
raise Exception('Failed to connect to %s' % url) from None
```

I found the above through the references, I mentioned earlier.

**Comment by qxf2** [comment]
No, @rahul-bhave . The .json() method has nothing to do with the error code. That is stored in status_code variable. For this ticket, you can first think if we really need to put that .json() method within a try-catch. If we do, you can simply use the generic `except Exception as e` and proceed.

**Comment by rahul-bhave** [comment]
> No, @rahul-bhave . The .json() method has nothing to do with the error code. That is stored in status_code variable. For this ticket, you can first think if we really need to put that .json() method within a try-catch. If we do, you can simply use the generic `except Exception as e` and proceed.

@qxf2 , the `try-catch` block is required in case there is an exception is generated while running response.json() then that can be captured in the except so I think this except is required.

**Comment by qxf2** [comment]
@rahul-bhave I'm not convinced but go ahead if you are confident. We can always enhance you change later.

**Comment by qxf2** [comment]
Upon thinking a bit more, I feel like this pattern of try within a try is incorrect. We should really add a second except to the first try statement that is generic and set json_response to None over there.

**Comment by rahul-bhave** [comment]
Following PR is merged hence closing the issue:
https://github.com/qxf2/qxf2-page-object-model/pull/254
