### ISSUE TITLE
Clean up trailing whitespaces in our code base

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#224]
Codacy notices 140 (!!) instances of trailing whitespace in our codebase. Please fix them using some tool/linter. 

Note: You should not be going manually to each line identified and removing the whitespace. Instead, you should look for a tool/plugin in VS Code that does this for you automatically.

https://app.codacy.com/manual/qxf2/qxf2-page-object-model/issues?bid=16560353&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE2MyJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

**Comment by rahul-qxf2** [comment]
This PR is created for below ticket:
https://github.com/qxf2/qxf2-page-object-model/issues/224

To fix trailing whitespace I did the following:
1. set `files.trimTrailingWhitespace": true` in the user settings (menu File → Preferences → Settings → User Settings tab). Save the user settings.

2. Save All the files. This will remove whitespaces.

**Comment by rahul-qxf2** [comment]
closing this issue as PR got merged.
