### ISSUE TITLE
CI is failing because mobile test is not roboust enough

### ISSUE THREAD

**Issue by Annapooraniqxf2** [qxf2/qxf2-page-object-model#230]
Noticed a failure in CI but after sometimes it passes.
**The reason for the failure is** 
 'Exception when trying to run test:/root/project/tests/test_mobile_bitcoin_price.py'

**The error is** 
 Python says:Message: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot get screenshot data because of 'Error executing adbExec. 
Original error: 'Command 'android-sdk/platform-tools/adb -P 5037 -s 2223c9981f0c7ece shell /system/bin/rm /data/local/tmp/screenshot.png\; /system/bin/screencap -p /data/local/tmp/screenshot.png' timed out after 20000ms'; Stderr: ''; Code: 'null''
 

 
FAILED
 
  
But important thing is test is not failing all the time it passes sometimes also

**Comment by akkuldn** [comment]
This issue was resolved by updating the appium version used in BrowserStack. The fix has been merged, Hereby closing this issue.
