### ISSUE TITLE
Fix PytestDeprecationWarning when running CI

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#232]
I notice warnings like this when CI runs:

```
/root/project/.tox/py36/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
 
Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.

``` 
 Note: Please do not just silence the warning. Try to move to xunit2 first and see if it work with our current version of pytest. 

This link might be useful: https://stackoverflow.com/a/60735580

**Comment by rahul-qxf2** [comment]
@qxf2 , Let me know in case this can be sent for code review:

[circleci tests](https://circleci.com/gh/qxf2/qxf2-page-object-model/839) are not showing this warning now. 
[[codacy tests]](https://app.codacy.com/manual/qxf2/qxf2-page-object-model/pullRequest?prid=5570672) are passing as well.

**Comment by rahul-qxf2** [comment]
Closing the issue as PR got merged and test run does not show this warning again.
https://app.circleci.com/pipelines/github/qxf2/qxf2-page-object-model/103/workflows/977b5ff9-7f65-4b3c-ae4b-ef7d3a5193fa/jobs/862
