### ISSUE TITLE
while running xpath_util.py exception ``Exception when trying to generate xpath for:input Python says can not concat string to bytes` generated.

### ISSUE THREAD

**Issue by rahul-bhave** [qxf2/qxf2-page-object-model#239]
While running xpath_util.py exception `Exception when trying to generate xpath for:input Python says can not concat string to bytes` generated.

Below is the output after fixing the issue:

```
$ python -u utils/xpath_util.py
Start of utils/xpath_util.py
Enter URL: https://qxf2.com/selenium-tutorial-main
input_name = //input[@id='name']
input_email = //input[@name='email']
input_phone = //input[@id='phone']
//input[@type='checkbox']----> Couldn't generate appropriate variable name for this xpath
button_gender = //button[contains(text(),'Gender')]
button_click_me = //button[text()='Click me!']

```

**Comment by rahul-qxf2** [comment]
# 239

**Comment by rahul-bhave** [comment]
@Annapooraniqxf2 , below are the details for the above PR:

Code
[ ] logical commits

I have updated the xpath_util.py code. All the discussion regarding this is at below Trello card.
the original issue was- 

`Exception when trying to generate xpath for input Python says can not concat string to bytes generated`

`https://github.com/qxf2/qxf2-page-object-model/issues/239`

`https://trello.com/c/cc9kAo2a/10-issue-239-while-running-xpathutilpy-exception-exception-when-trying-to-generate-xpath-forinput-python-says-can-not-concat-string`

[ ] matches the task description

Yes.

[ ] passes pylint (>9.0)
I have check pylint logs on this particular file and most of the logs are not for these changes.

[ ] passes radon (A for new code)
radon log is as below-

```
$ radon cc utils/xpath_util.py -a
utils/xpath_util.py
    M 77:4 Xpath_Util.get_variable_names - D
    M 28:4 Xpath_Util.generate_xpath - C
    C 16:0 Xpath_Util - B
    M 123:4 Xpath_Util.guess_xpath - A
    M 19:4 Xpath_Util.__init__ - A
    M 134:4 Xpath_Util.guess_xpath_button - A
    M 140:4 Xpath_Util.guess_xpath_using_contains - A

7 blocks (classes, functions, methods) analyzed.
Average complexity: B (8.0)
```

[ ] use VS code settings
Yes

[ ] add a source if you copy code from somewhere
Yes

[ ] no long methods (< 10 lines)
Did not add any new methods only existing code is modified.

[ ] good names for methods and variables and classes
Did not add any new code only existing code is modified.

[ ] consistent naming schemes
Did not add any new code only existing code is modified.

[ ] comments should outline TODO
In the modified code there is no to-do list hence no TODO comment mentioned in the file.

[ ] rebase your code before creating a PR
The PR was created before we apply this new coding guideline. I have squashed most of the code, however, only `conftest.py` changes are still showing this PR. I have compared the file and could not spot any difference, I think during rebase some additional code was added and that has to be removed.

[ ] squash your code
Done most of the commit squashing however 7 commits are there as most of those are rebasing master, test failure and undoing changes like `README.md`

Presenting the PR

[ ] what change should the code reviewer expect visually?

1. Added decode('latin-1') next to encode('utf-8')
2. Removed code added for other guessable elements other than button and input
3. Changed `self.variable_name = element['placeholder'].strip("_?*.").encode('ascii',errors='ignore')` to `self.variable_name = element['placeholder']`

[ ] what files did you change?
All the changes are in xpath_util.py

[ ] how did you test the change?

All the testing details are available at Trello card-
`https://trello.com/c/cc9kAo2a/10-issue-239-while-running-xpathutilpy-exception-exception-when-trying-to-generate-xpath-forinput-python-says-can-not-concat-string`

There are two issues existing for which one new issue will be opened all the details are at the above Trello card.

[ ] what explicit tradeoff did you make?
Fixed the issue- `https://github.com/qxf2/qxf2-page-object-model/issues/239`

[ ] how to run the change

python utils/xpath_util.py
Then provide the website to get xpaths,

I have tested this for around 50 websites. Details are at- 
`https://trello.com/c/cc9kAo2a/10-issue-239-while-running-xpathutilpy-exception-exception-when-trying-to-generate-xpath-forinput-python-says-can-not-concat-string`
