### ISSUE TITLE
Support only descriptive CLI options and add default values to the options

### ISSUE THREAD

**Issue by shivahari** [qxf2/qxf2-page-object-model#246]
The CLI options the framework supports should be more descriptive.
```
parser.addoption("-B","--browser",
                            dest="browser",
                            action="append",
                            default=[],
                            help="Browser. Valid options are firefox, ie and chrome")
```
here `--browser` is more useful than `-B`. Modify all options in `conftest.py` file to support the descriptive options only

Set default values for the options. The default value for `--browser` is  `[]` with the current implementation, it should be `['chrome']` or `['firefox']`. Modify all options to set default values.

**Comment by rahul-bhave** [comment]
closing this issue as PR for this merged now.
