### ISSUE TITLE
Unused method def record() in utils/results.py

### ISSUE THREAD

**Issue by Annapooraniqxf2** [qxf2/qxf2-page-object-model#249]
We have a unused method record() which is defined in the utils/result.py 
Please remove that method

**Comment by rahul-bhave** [comment]
I have created PR:
https://github.com/qxf2/qxf2-page-object-model/pull/268

All details are mentioned in PR. #268

**Comment by rahul-bhave** [comment]
Closing this ticket as PR#268 is closed.
