### ISSUE TITLE
Provide support of MS Edge browser in driverfactory.py file.

### ISSUE THREAD

**Issue by rahul-bhave** [qxf2/qxf2-page-object-model#281]
New MS Edge is using a chromium engine. So we should also support this in the driverfactory.py file.

I think the below code should add it, I am not sure, need to check this once again-

```
elif browser.lower() == "edge":
local_driver=webdriver.Edge("msedgedriver.exe")
```

**Comment by HarshCasper** [comment]
I would like to work on this Issue. Kindly assign this to me.
