### ISSUE TITLE
Add pre-commit hooks to make sure credentials files do not change

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#284]
Please add a pre-commit hook to make sure the credential files within conf do not change. This is to ensure we never leak our BrowserStack, Sauce Labs, TestRail (and other?) credentials.

**Comment by rohit679** [comment]
I would like to work upon this issue, please assign it to me.

**Comment by avinash010** [comment]
@rohit679 You can create a fork and start working on any issue. Once done please create a PR

**Comment by rohit679** [comment]
Here, I am adding the steps & code for writing Pre-commit hook, for preventing changes to the credential files.

- First make the vscode settings for accessing hidden .git files within vscode
- Go to settings & search for file.exclude then set { "**/.git" : false} & you are good to go
- Then go inside .git / hooks/pre-commit.sample & comment previous given stuff by selecting all(ctrl+a) and press (ctrl+/).
- Copy the given code below and paste it into the file.
`#!/bin/sh
# full paths from the repo root separated by newlines
MUST_NOT_CHANGE='conf/api_example_conf.py
conf/remote_credentials.py
conf/email_conf.py
conf/ssh_conf.py
conf/testrailenv_conf.py
conf/tesults_conf.py'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exec 1>&2

if git diff --cached --name-only $against |
   grep --quiet --line-regexp --fixed-strings "$MUST_NOT_CHANGE"
then
  echo Commit would modify one or more files that should not change.
  exit 1
else
  exit 0
fi`
- Rename the file to pre-commit [remove .sample]
- Then make that file executable, go the directory where this file stored via Git Bash & run following -
 `chmod +x pre-commit`
