### ISSUE TITLE
"wait_time" is not defined  

### ISSUE THREAD

**Issue by tokAshraf** [qxf2/qxf2-page-object-model#304]
In Mobile_Base_Page class 
Def: smart_wait
"wait_time" is not defined
<img width="663" alt="fix" src="https://user-images.githubusercontent.com/81229031/179959364-da34f13c-2630-47be-93c8-f7b693880669.png">

**Comment by qxf2** [comment]
Fixed as part of [PR-305](https://github.com/qxf2/qxf2-page-object-model/pull/305)
