### ISSUE TITLE
Options to pass on remote testing not working 

### ISSUE THREAD

**Issue by drishyatm** [qxf2/qxf2-page-object-model#364]
Remote testing ( browserstack and saucelabs) would be taking the parameters as which browser /version to test . 
However noticed that the option passing as browser is throwing error message as "list index out of range" 

While we run the test using the command 
python -m pytest tests/test_example_form.py --remote_flag Y  --browser firefox

**Comment by avinash010** [comment]
While fixing this. Can you also change the version of chrome and Firefox to latest version
