### ISSUE TITLE
Add a way to email pytest results 

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#39]
Slack integration is fantastic. But I can see some use cases where we may want to email a set of people. Can we add a hook to pytest so it emails results?

**Comment by rohandudam** [comment]
Yes, we can add a hook to pytest to email results to a set of people.

**Comment by indiranell** [comment]
Verified sending test report email for below scenarios

- Get html formatted email

- Get text formatted email

- Add html formatted email message along with an attachment file

- Add text formatted email message along with an attachment file
