### ISSUE TITLE
Update the project wiki to replace the deprecated CLI parameters with the right ones

### ISSUE THREAD

**Issue by shivahari** [qxf2/qxf2-page-object-model#418]
The project wiki still seems to be using the old and now deprecated CLI parameters, like in this statement `python -m pytest -k example_form -B Chrome` in https://github.com/qxf2/qxf2-page-object-model/wiki/Setup the `-B` CLI parameter needs to be replaced by `--browser` parameter.

Identify and replace the deprecated CLI parameters with the right ones

**Comment by rohandudam** [comment]
@shivahari I checked wiki pages and updated deprecated CLI parameters. Can you please review it and let me know if I missed anything.

**Comment by shivahari** [comment]
@rohandudam Is this link in the [Setup](https://github.com/qxf2/qxf2-page-object-model/wiki/Setup) page in scope of this task?
<img width="1248" alt="setup_testrail_integration_link" src="https://github.com/user-attachments/assets/5d6f3233-488d-4c11-b26e-25bb0caa2c44">

Clicking on it takes me to a new page. 
Rest all looks good 👍

**Comment by rohandudam** [comment]
@shivahari Thanks for catching that bad link. Its not in scope of this issue but I fixed it too.

**Comment by rohandudam** [comment]
Done with the changes and changes reviewed by Shiva. 
Good to close this issue.
