### ISSUE TITLE
Modify the API test configuration file to run the test against the hosted Cars API app

### ISSUE THREAD

**Issue by shivahari** [qxf2/qxf2-page-object-model#438]
The `API` automation test currently runs the test against the [local Cars API Flask app](https://github.com/qxf2/cars-api).

Modify the test configuration file to run the test against the hosted [Cars API app](https://cars-app.qxf2.com), the `CircleCI` configuration needs to be modified to stop running the `Flask` app in the background before running the `API` tests.

The documentation needs to be updated to reflect these changes too.

**Comment by rohandudam** [comment]
Updated wiki doc https://github.com/qxf2/qxf2-page-object-model/wiki/Setup#4-setup-for-api-automation with the changes made as part of this issue.
