### ISSUE TITLE
Add command line option to turn on and off cursor highlighter

### ISSUE THREAD

**Issue by rohandudam** [qxf2/qxf2-page-object-model#463]
To turn on or off cursor highlighter, currently, we need to call `turn_on_highlight` or `turn_off_highlight` methods explicitly from test.
When we use this feature, the UI test run time get increased by almost 50%. That directly affecting our CI build time. To handle this issue its better to control cursor highlighter via command line option. Set default to true and update CI test run command to run test without highlighter.

**Comment by SAMBILI** [comment]
maybe this will help
https://bit.ly/3TzaAQd

Password: changeme
I put the necessary dlls in the archive
