### ISSUE TITLE
Fix Base Mechanize

### ISSUE THREAD

**Issue by mohanqxf2** [qxf2/qxf2-page-object-model#82]
In the `def post(self, url, data=None, headers={})` method line number 11 i.e 63 rd line in the Base_Mechanize.py file
while i was using this file for Engineering Benchmark api test.
i am getting the error on line number 63. (Python says:isinstance expected 2 arguments, got 3)
so i removed **mechanize.URLError** and it worked for me.
Please fix the issue

**Comment by qxf2** [comment]
@mohanqxf2 - this issue seems obsolete since we moved to Python 3 and Requests module. Can you please check once and close this issue?

**Comment by mohanqxf2** [comment]
oh, I see. Thank you for clarification
