### ISSUE TITLE
Set correct log file name for providing support to pytest-xdist plugin.

### ISSUE THREAD

**Issue by raddhakrishnan** [qxf2/qxf2-page-object-model#83]

**Comment by qxf2** [comment]
@rohinigopalqxf2 - I believe your work has already fixed this issue? Can you please check once and then close this issue?

**Comment by rohinigopalqxf2** [comment]
I will check this as I cannot recollect right now.

**Comment by rohinigopalqxf2** [comment]
This was fixed
